# Generated by Django 5.1.4 on 2024-12-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('anio', models.IntegerField()),
                ('modelo', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Paleta',
        ),
    ]
