# Generated by Django 5.1.4 on 2024-12-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_moto_delete_paleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='motos'),
        ),
    ]
